import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import PublicNavbarWrapper from "@/components/PublicNavbarWrapper";
import { ThemeProvider } from "@/components/theme-provider"
import SessionWrapper from "@/components/SessionWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-p-20 scroll-smooth" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionWrapper>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        {/* ✅ Navbar only for public routes */}
          <PublicNavbarWrapper />
        {children}
        </ThemeProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}
